name: bjj_timer
description: "BJJ timer for every open mat"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.0.1
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
